# Generated by Django 5.2.6 on 2025-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Описание')),
                ('lng', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Шировата')),
            ],
        ),
    ]
