# Generated by Django 5.2.6 on 2025-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number'], 'verbose_name': ('Картинка',), 'verbose_name_plural': 'Фотография '},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': ('Место',), 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Широта'),
        ),
    ]
