# Generated by Django 5.2.6 on 2025-10-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lng', 'lat')},
        ),
    ]
