# Generated by Django 5.2.6 on 2025-10-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number'], 'verbose_name': ('Картинка',), 'verbose_name_plural': 'Фотографии'},
        ),
    ]
