# Generated by Django 5.2.6 on 2025-10-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
